#!/usr/bin/env bash

function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}

#herbstluftwm start
hc() {
    herbstclient "$@"
}

hc emit_hook reload

# KEYBINDINGS

# remove all existing keybindings
hc keyunbind --all

Mod=Mod4                            # Use the super key as the main modifier
myTerm=alacritty                    # Set my preferred terminal
myEditor="emacsclient -c -a emacs"  # Set my preferred editor

hc keybind $Mod-Shift-x quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close


hc keybind $Mod-Return spawn $myTerm
hc keybind $Mod-e spawn $myEditor
hc keybind Mod1-Control-Return spawn  ./xmenu/xmenu.sh

# Dmenu launcher
hc keybind $Mod-Shift-d spawn dmenu_run -fn 'Mononoki Nerd Font:size=10' -nb '#292d3e' -nf '#bbc5ff' -sb '#82AAFF' -sf '#292d3e' -p 'dmenu:'
hc keybind $Mod-Shift-Return spawn pcmanfm

hc keybind $Mod-d spawn nwggrid -p -o 0.4

# My dmenu scripts (Alt+Ctrl+Key)
hc keybind Mod1-Control-e spawn ./.dmenu/dmenu-edit-configs.sh
hc keybind Mod1-Control-m spawn ./.dmenu/dmenu-sysmon.sh

# My applications (Super+Alt+Key)
hc keybind $Mod-Mod1-j spawn $myTerm -e joplin

# focusing clients
hc keybind $Mod-Left          focus left
hc keybind $Mod-Down          focus down
hc keybind $Mod-Up            focus up
hc keybind $Mod-Right         focus right
hc keybind $Mod-h             focus left
hc keybind $Mod-j             focus down
hc keybind $Mod-k             focus up
hc keybind $Mod-l             focus right
                              
# moving clients              
hc keybind $Mod-Shift-Left    shift left
hc keybind $Mod-Shift-Down    shift down
hc keybind $Mod-Shift-Up      shift up
hc keybind $Mod-Shift-Right   shift right
hc keybind $Mod-Shift-h       shift left
hc keybind $Mod-Shift-j       shift down
hc keybind $Mod-Shift-k       shift up
hc keybind $Mod-Shift-l       shift right

# splitting frames
hc keybind $Mod-u             split  bottom  0.5
hc keybind $Mod-o             split  right   0.5
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h      resize left +$resizestep
hc keybind $Mod-Control-j      resize down +$resizestep
hc keybind $Mod-Control-k      resize up +$resizestep
hc keybind $Mod-Control-l      resize right +$resizestep
hc keybind $Mod-Control-Left   resize left +$resizestep
hc keybind $Mod-Control-Down   resize down +$resizestep
hc keybind $Mod-Control-Up     resize up +$resizestep
hc keybind $Mod-Control-Right  resize right +$resizestep
hc keybind $Mod-r remove

# tags
tag_names=(" 1 " " 2 " " 3 " " 4 " " 5 " " 6 " " 7 " " 8 " " 9 ")
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-t floating toggle
hc keybind $Mod-space fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-Tab                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-n         cycle_all +1
hc keybind $Mod-Shift-n   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#ff4500'
hc set frame_border_normal_color '#f4c2c2'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#dd2727'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_padding 0
hc set focus_follows_mouse 1

hc attr theme.active.color '#c678dd'
hc attr theme.normal.color '#e06c75'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#282c34'
hc attr theme.active.outer_color '#282c34'
hc attr theme.background_color '#ffffff'

hc set frame_gap 5
hc set window_gap 5
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_crosses_monitor_boundaries 1
hc set swap_monitors_to_get_tag 1

#Space for polybar
hc pad 0 20

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule class=VirtualBox tag=5 # move all VMs to tag 5
hc rule title='Oracle VM VirtualBox Manager' tag=5 
hc rule class=VirtualBox pseudotile=on
hc rule class=VirtualBox fullscreen=on
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors
# hc set_monitors 1920x1060+0+20 1920x1060+1920+20 1920x1060+3840+20
herbstclient set_monitors 1920x1080+0+0
# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

#Autostart applications
dunst &
# lxsession &
# polkit-dumb-agent &

xsetroot -solid '#5A8E3A'
# xsetroot -cursor_name left_ptr &
feh --bg-fill /home/rohits/mydata/home/Pictures/wallpapers/0051.jpg &
/home/rohits/.config/herbstluftwm/hlwm

#keybindings are in config of sxhkd - interchangeable with other TWM
sxhkd -c ~/.config/herbstluftwm/sxhkd/sxhkdrc &

run nm-applet &
#numlockx on &
#blueberry-tray 

#feh --bg-scale ~/.config/herbstluftwm/wall.png &
# feh --bg-fill /usr/share/backgrounds/arcolinux/arco-wallpaper.jpg &
#feh --bg-scale /usr/share/backgrounds/arcolinux/abstract-warm-heart-4560x2160.jpg
# picom  --config $HOME/.config/picom/picom.conf &

pamac-tray &
run volumeicon &

export QT_QPA_PLATFORMTHEME=qt5ct
# run emacs --daemon &
