#!/usr/bin/env python
import json
import subprocess

def run(*processes):
    for process in processes:
        pn = process.split()[0]
        if bool(subprocess.run(["pgrep", pn], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode):
            subprocess.Popen(process.split(), shell=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            # print(f"Not Running {pn}")
            # print(process.split())

def hc_kb(keys):
    """ Keybindings set"""
    for key in keys:
        subprocess.run(["herbstclient", "keybind", key, keys[key]])
    


mod = "Mod4"
myTerm = "alacritty"
myEditor = "emacsclient -c -a emacs"

keys = '''{
    "Mod4-Shift-x" : "quit", 
    "Mod4-Shift-r" : "reload"
    }'''


keyd = json.loads(keys)

# for key in keyd:
    # print(key, " : ", keyd[key])

# print(type(keyd))
# print(keyd["k2"])

# print('''{ hello{{0}}}'''.format(mod))


run(
    "picom",
    # "alacritty",
    # "feh --randomize --bg-fill /home/rohit/Pictures/wallpapers/*.jpg"
    "feh --bg-fill /home/rohit/Pictures/wallpapers/0051.jpg"
)

